resources:
  App\Entity\Exam:
    collectionOperations:
      post:
        controller: App\Controller\CreateNewExamController
        normalization_context:
          groups: ['exam:read']
    itemOperations:
      get:
    attributes:
      security: 'is_granted("ROLE_USER")'
      normalization_context:
        groups: ['exam:read']
      denormalization_context:
        groups: ['exam:write']
  App\Entity\User:
    itemOperations:
      get:
      put:
      delete:
    collectionOperations:
      get:
      post:
    attributes:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: ['user:read']
      denormalization_context:
        groups: ['user:write']
  App\Entity\StatusCode:
    itemOperations:
      get:
      put:
        normalization_context:
          groups: ['statuscode:put']
    collectionOperations:
      post:
        normalization_context:
          groups: ['statuscode:post']
      get:
    attributes:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: ['statuscode:get']
