resources:
  App\Entity\Question:
    collectionOperations: []
    itemOperations:
      get: ~
      put:
        security: 'is_granted("ANSWER_QUESTION", object)'
    attributes:
      security: 'is_granted("ROLE_ADMIN")'
      denormalization_context:
        groups: ['question:write']
      normalization_context:
        groups: ['question:read']
  App\Entity\Exam:
    collectionOperations:
      get: ~
      post:
        controller: App\Controller\CreateNewExamController
        normalization_context:
          groups: ['exam:read']
    itemOperations:
      get:
    attributes:
      security: 'is_granted("ROLE_USER")'
      normalization_context:
        groups: ['exam:read']
      denormalization_context:
        groups: ['exam:write']
  App\Entity\User:
    itemOperations:
      get:
      put:
      delete:
      post_enable_mfa:
        method: 'POST'
        path: '/users/{id}/mfa_enable'
        controller: App\Controller\EnableMultiFactorAuthentication
        security: 'is_granted("ROLE_ADMIN") or object == user'
      post_disable_mfa:
        method: 'POST'
        path: '/users/{id}/mfa_disable'
        controller: App\Controller\DisableMultiFactorAuthentication
        security: 'is_granted("ROLE_ADMIN") or object == user'
    collectionOperations:
      get:
      post:
    attributes:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: ['user:read']
      denormalization_context:
        groups: ['user:write']
  App\Entity\StatusCode:
    itemOperations:
      get:
      put:
        normalization_context:
          groups: ['statuscode:put']
    collectionOperations:
      post:
        normalization_context:
          groups: ['statuscode:post']
      get:
    attributes:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: ['statuscode:get']
  App\Entity\MultiFactorAuthenticationVerify:
    itemOperations: []
    collectionOperations:
      post:
        path: '/mfa_verify'
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        controller: App\Controller\VerifyMultiFactorAuthentication

#  App\Entity\MultiFactorAuthenticationEnable:
#    itemOperations: []
#    collectionOperations:
#      post:
#        path: '/mfa_enable'
#        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
#        controller: App\Controller\EnableMultiFactorAuthentication
#
#  App\Entity\MultiFactorAuthenticationDisable:
#    itemOperations: []
#    collectionOperations:
#      post:
#        path: '/mfa_disable'
#        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
#        controller: App\Controller\DisableMultiFactorAuthentication
