name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check PSR
      run: vendor/bin/php-cs-fixer fix --diff --dry-run -v

    - name: Install phpunit
      run: bin/phpunit install

    - name: Run test
      run: bin/phpunit

    - name: Run phpstan
      run: vendor/bin/phpstan analyse src tests --level max
